export const pages = [
['','Road Users'],['pedestrians','Pedestrians'],['cyclists','Cyclists'],
['motorcyclists','Motorcyclists'],['motorcyclists/safe-motorcycling','Safe motorcycling'],['motorcyclists/motorcycle-maintenance-and-standards','Motorcycle maintenance and standards'],['motorcyclists/motorcycle-safety-gear','Motorcycle safety gear'],['motorcyclists/medical-fitness','Medical fitness'],
['passengers','Passengers'],['passengers/children','Children'],['passengers/pregnant-women','Pregnant women'],['passengers/adults','Adults'],['passengers/public-vehicle-passengers','Public vehicle passengers'],['passengers/pillion-passengers','Pillion passengers'],
['car-drivers','Car drivers'],['car-drivers/car-maintenance','Car maintenance'],['car-drivers/car-safety','Vehicle safety'],['car-drivers/modified-vehicles','Modified vehicles'],['car-drivers/buying-selling-a-car','Buying & selling a car'],['car-drivers/light-trailers','Light trailers'],['car-drivers/medical-fitness','Medical fitness'],['car-drivers/faqs','FAQs'],
['professional-drivers','Professional drivers'],['professional-drivers/driving-for-work','Driving for work'],['professional-drivers/health-safety','Health & safety'],['professional-drivers/complaints','Complaints'],['professional-drivers/medical-fitness','Medical fitness'],['professional-drivers/vehicle-safety-legislation','Vehicle safety & legislation'],
['agricultural-vehicle-drivers','Agricultural vehicle drivers'],['agricultural-vehicle-drivers/introduction','Introduction'],['agricultural-vehicle-drivers/agricultural-tractors','Agricultural tractors'],['agricultural-vehicle-drivers/class-r-agricultural-trailers','Class R agricultural trailers'],['agricultural-vehicle-drivers/towing-rules','Towing rules'],['agricultural-vehicle-drivers/braking-laws-for-agricultural-tractors','Tractor braking laws'],['agricultural-vehicle-drivers/braking-laws-for-class-r-agricultural-trailers','Trailer braking laws'],['agricultural-vehicle-drivers/lighting-and-visibility-laws','Lighting and visibility'],['agricultural-vehicle-drivers/work-or-ploughing-lamps','Work or ploughing lamps'],['agricultural-vehicle-drivers/couplings','Couplings'],['agricultural-vehicle-drivers/seatbelts','Seatbelts'],['agricultural-vehicle-drivers/speed-ratings','Speed ratings'],['agricultural-vehicle-drivers/plating','Plating'],['agricultural-vehicle-drivers/quad-bikes-and-atvs','Quad bikes and ATVs'],
['connected-and-autonomous-vehicles','Connected and autonomous vehicles'],['vintage','Vintage vehicles'],
['special-purpose-vehicles','Drivers of other vehicles'],['special-purpose-vehicles/introduction','Introduction'],['special-purpose-vehicles/e-scooters','E-scooters'],['special-purpose-vehicles/e-bikes-and-e-mopeds','E-bikes and e-mopeds'],['special-purpose-vehicles/special-purpose-vehicles','Special purpose vehicles'],['special-purpose-vehicles/wheelchair-accessible-vehicles','Wheelchair accessible vehicles'],['special-purpose-vehicles/motorised-wheelchairs-and-mobility-scooters','Motorised wheelchairs and mobility scooters'],['special-purpose-vehicles/motorhomes','Motorhomes and camper vans'],['special-purpose-vehicles/trailer-caravans','Trailer caravans'],['special-purpose-vehicles/small-public-service-vehicles','Small public service vehicles'],['special-purpose-vehicles/golf-buggies-and-ride-on-lawnmowers','Golf buggies and ride-on lawnmowers'],['special-purpose-vehicles/rickshaws','Rickshaws and tuk-tuks'],['special-purpose-vehicles/mobile-machines-and-works-vehicles','Mobile machines and works vehicles'],['special-purpose-vehicles/armoured-and-custodial-vehicles','Armoured and custodial vehicles'],['special-purpose-vehicles/hearses','Hearses'],
['horse-drawn','Animals on roads'],['tourists','Tourists'],['tourists/advice-for-ukrainian-drivers','Advice for Ukrainian drivers'],
['vehicle-components','Vehicle components'],['vehicle-components/vehicle-lighting','Vehicle lighting'],['vehicle-components/seatbelts-and-child-restraints','Seatbelts and child restraints'],['vehicle-components/vehicle-glass','Vehicle glass'],['vehicle-components/tyres','Tyres'],['vehicle-components/frontal-protection-systems','Frontal protection systems'],['vehicle-components/adblue','AdBlue'],['legislation','Legislation']
];
